"""create families

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-28 19:28:47.263923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_families_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_families'))
    )
    op.create_table('family_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'declined', 'cancelled')", name=op.f('ck_family_invitations_status')),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_family_invitations_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_family_invitations_invited_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], name=op.f('fk_family_invitations_invitee_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_invitations'))
    )
    with op.batch_alter_table('family_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_invitations_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_invitations_invitee_id'), ['invitee_id'], unique=False)

    op.create_table('family_members',
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=6), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'member')", name=op.f('ck_family_members_role')),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_family_members_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_family_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('family_id', 'user_id', name=op.f('pk_family_members'))
    )
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_members_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_members_user_id'))

    op.drop_table('family_members')
    with op.batch_alter_table('family_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_invitations_invitee_id'))
        batch_op.drop_index(batch_op.f('ix_family_invitations_family_id'))

    op.drop_table('family_invitations')
    op.drop_table('families')
    # ### end Alembic commands ###
